### PR TITLE
[Issue-12] customer structure

### LINKED ISSUE #12: Create Customer directory and UI set up

### PR DESCRIPTION
**Pull request by sonechca**
fixes: #12 

## Description

Add new feature: Customer structure
I created a profile page and editing page but we need to connect later

Screen Shot 2021-01-23 at 9 40 14 PM

### CODE REVIEW

**Review by eunbeek — APPROVED** [review]
I resolved one conflict that it happens for the previous PR.

**Comment by sonechca** [comment]
> I resolved one conflict that it happens for the previous PR.

Thank you

**Comment by yuanLeeMidori** [comment]
How to access CustomerProfile, CustomerProfilEdit? Any router setting for them? Or still work-in-progress?

CustomerHome is fine.

**Comment by yuanLeeMidori** [comment]
Ahh nvm I saw your description. Please go ahead and merge this PR.

**Review by yuanLeeMidori — APPROVED** [review]

**Pull request merged**
