### PR TITLE
Test the customer profile page to get data from database

### PR DESCRIPTION
**Pull request by sonechca**
Screen Shot 2021-02-23 at 12 20 33 AM

2021/2/28

Add getCustomer, editCustomer, getAdminCustomers, getAdminCustomer

### CODE REVIEW

**Comment by yuanLeeMidori** [comment]
image
Tested, works fine.

**Comment by yuanLeeMidori** [comment]
tips from Clint:
use hidden type

**Comment by sonechca** [comment]
Added Edit function

**Review by yuanLeeMidori — CHANGES_REQUESTED** [review]
You use `${process.env.REACT_APP_API_URL}` in your branch, however, your `.env` does not have this variable. Please rebase it and then test your branch and make sure it works.

**Review by eunbeek — DISMISSED** [review]

**Review by yuanLeeMidori — CHANGES_REQUESTED** [review]
image
Should the "memo" field be saved after edit as well? It doesn't seem to be saved.
Also, can we change "edit" button in this page to "save" instead? Thank you.
And, "cancel" and "back to home" seem to both link to customer home page. Can we just use one?

**Comment by sonechca** [comment]
Changed button link and name, but Memo and address part is not available yet. I will update this part after creating signup page

**Review by eunbeek — APPROVED** [review]

**Review by yuanLeeMidori — APPROVED** [review]

**Pull request merged**
